import {
  LayoutDashboard,
  Users,
  DoorOpen,
  ShoppingBag,
  Wallet,
  Package,
  History,
  ChartNoAxesCombined,
  MessageSquare,
  CalendarDays,
  Settings2,
} from 'lucide-react'
export const modules = [
  {
    id: 'overview',
    label: 'Overview',
    icon: LayoutDashboard,
    group: 'Workspace',
    description: 'Keep track of visits, rooms, and lockers.',
    features: [],
  },
  {
    id: 'members',
    label: 'Members',
    icon: Users,
    group: 'Workspace',
    description: 'Memberships, member records, and admission status.',
    features: [
      'Create and renew memberships',
      'Member notes, tags, and do-not-admit flags',
      'Waivers, signatures, and attachments',
      'Membership import and member history',
    ],
  },
  {
    id: 'activity',
    label: 'Admissions & rentals',
    icon: DoorOpen,
    group: 'Workspace',
    description: 'Keep track of visits, rooms, and lockers.',
    features: [
      'Check-in and checkout',
      'Room and locker assignments',
      'Rental extensions and expiration',
      'Waitlist and in/out tracking',
    ],
  },
  {
    id: 'sales',
    label: 'Point of sale',
    icon: ShoppingBag,
    group: 'Operations',
    description: 'Memberships, rentals, and retail in one checkout.',
    features: [
      'Quick sale and member-linked orders',
      'Discounts, taxes, returns, and waived products',
      'Split cash, credit card, and gift card tender',
      'Suspended orders and printed or emailed receipts',
    ],
  },
  {
    id: 'registers',
    label: 'Registers',
    icon: Wallet,
    group: 'Operations',
    description: 'Track each drawer from opening to reconciliation.',
    features: [
      'Open and close a shift',
      'Cash denominations and drawer reconciliation',
      'Cash drops and payout tracking',
      'Shift reports and QuickBooks invoices',
    ],
  },
  {
    id: 'products',
    label: 'Products',
    icon: Package,
    group: 'Operations',
    description: 'Your membership, rental, and retail catalog.',
    features: [
      'Categories and product images',
      'Prices, taxes, barcodes, and inventory',
      'Membership and rental durations',
      'Restricted, core, and payout products',
    ],
  },
  {
    id: 'history',
    label: 'History',
    icon: History,
    group: 'Insights',
    description: 'Find past visits and transactions.',
    features: [
      'Search by member, date, or order ID',
      'Activity and order history',
      'Receipt reprints',
      'Permission-controlled voids',
    ],
  },
  {
    id: 'reports',
    label: 'Reports & analytics',
    icon: ChartNoAxesCombined,
    group: 'Insights',
    description: 'Understand sales, attendance, and shift performance.',
    features: [
      'Date-range membership, attendance, and sales analysis',
      'Excel reports and daily summaries',
      'Scheduled daily report delivery',
      'QuickBooks accounting integration',
    ],
  },
  {
    id: 'messages',
    label: 'Messages',
    icon: MessageSquare,
    group: 'Administration',
    description: 'Staff conversations and system announcements.',
    features: [
      'Staff-to-staff conversations (legacy navigation disabled)',
      'Chat message subscriptions',
      'Expiring system announcements',
    ],
  },
  {
    id: 'events',
    label: 'Events',
    icon: CalendarDays,
    group: 'Administration',
    description: 'Club scheduling.',
    features: ['Legacy calendar prototype only', 'Event storage and workflows still need design'],
  },
  {
    id: 'settings',
    label: 'Settings',
    icon: Settings2,
    group: 'Administration',
    description: 'Your account and application information.',
    features: [
      'Staff accounts and individual permissions',
      'Club settings, waivers, and receipt templates',
      'Integrations, support, and update delivery',
    ],
  },
] as const
export type ModuleId = (typeof modules)[number]['id']
